"""
Tariff recommender pipeline for mobile operators (Azercell-priced).

Run: python3 pipeline.py
Requires: telecom_users.csv, test_same_dist.csv, test_drift_x1.3.csv
          (and their *_hidden_types.csv eval-only companions)
          generated by gen_sections.py in the same directory.

Stages:
  1. Feature engineering
  2. Persona discovery (K-Means k=12 -> merged to named personas)
     evaluated against hidden_type (eval-only) via silhouette + ARI
  3. Persona classifier: LogisticRegression vs RandomForest vs
     HistGradientBoosting, 5-fold stratified CV
  4. Package builder: S/M/L tiers per persona, dedicated buckets for
     sections >= 2 GB, formula-priced and capped vs real existing offers
  5. recommend(user) end-to-end
  6. Economics evaluation vs best-fit existing Azercell offer
  7. Held-out (same-dist) and drift (x1.3) testing
  8. Sensitivity analysis + hand-crafted demo users

No fabricated numbers: every figure printed below is computed from the
data actually generated in this run.
"""

import json
import time

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    adjusted_rand_score,
    classification_report,
    confusion_matrix,
    f1_score,
    silhouette_score,
)
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.preprocessing import StandardScaler

RNG_SEED = 7
SECTIONS = ["social_media_gb", "video_streaming_gb", "communication_gb", "collaboration_gb", "ai_apps_gb", "gaming_gb"]
APP_COLS = [
    "tiktok_gb", "instagram_gb", "youtube_gb", "netflix_gb",
    "whatsapp_gb", "teams_gb", "chatgpt_gb", "claude_gb", "gemini_gb",
]

# ---------------------------------------------------------------------------
# Real Azercell price research (see docs/tariff-price-research.md).
# VERIFIED = scraped from azercell.com/app. ASSUMED = inferred, disclosed.
# ---------------------------------------------------------------------------
EXISTING_OFFERS = [
    # (gb, price_azn, source)
    (3, 9, "verified_28day"),
    (6, 12, "verified_28day"),
    (12, 19, "verified_28day"),
    (30, 29, "verified_28day"),
    (56, 39, "verified_28day"),
    (60, 60, "verified_premium_plus"),
    (100, 90, "verified_premium_plus"),
    (5, 12, "assumed_digimax"),
    (10, 18, "assumed_digimax"),
    (25, 30, "assumed_digimax"),
]


def cheapest_existing_offer(gb: float) -> tuple[float, str]:
    """Cheapest real/assumed offer with capacity >= gb. Falls back to the
    fitted formula (5.27*sqrt(gb)) if gb exceeds every listed offer."""
    candidates = [(price, src) for cap, price, src in EXISTING_OFFERS if cap >= gb]
    if candidates:
        price, src = min(candidates, key=lambda x: x[0])
        return price, src
    return round(5.27 * np.sqrt(gb), 2), "fitted_formula_extrapolated"


# ---------------------------------------------------------------------------
# 1. Feature engineering
# ---------------------------------------------------------------------------
def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    f = pd.DataFrame(index=df.index)
    total = df[SECTIONS].sum(axis=1).clip(lower=1e-6)
    f["total_gb"] = total
    for s in SECTIONS:
        f[f"log_{s}"] = np.log1p(df[s])
        f[f"share_{s}"] = df[s] / total
    yt_nf = df["youtube_gb"] + df["netflix_gb"]
    f["yt_vs_netflix"] = df["youtube_gb"] / yt_nf.clip(lower=1e-6)
    tt_ig = df["tiktok_gb"] + df["instagram_gb"]
    f["tiktok_vs_instagram"] = df["tiktok_gb"] / tt_ig.clip(lower=1e-6)
    return f


# ---------------------------------------------------------------------------
# 2. Persona discovery via K-Means(k=12) merged to named personas
# ---------------------------------------------------------------------------
NAMED_PERSONAS = [
    "Light user",
    "Heavy Video streamer (YouTube)",
    "Video streamer (Netflix)",
    "Everyday all-rounder",
    "Remote worker (Teams/Zoom)",
    "Social scroller (TikTok)",
    "Gamer",
    "Messaging-first (WhatsApp)",
    "Social scroller (Instagram)",
    "AI power user",
]


def name_cluster(center_shares: pd.Series, total_gb: float) -> str:
    """Rule-based naming of a cluster centroid onto one of the 10 named
    personas, using its dominant section share and total usage."""
    dominant = center_shares.idxmax()
    dom_share = center_shares[dominant]

    if total_gb < 4.5 and dom_share < 0.45:
        return "Light user"
    if dominant == "gaming_gb" and dom_share > 0.35:
        return "Gamer"
    if dominant == "ai_apps_gb" and dom_share > 0.25:
        return "AI power user"
    if dominant == "collaboration_gb" and dom_share > 0.25:
        return "Remote worker (Teams/Zoom)"
    if dominant == "communication_gb" and dom_share > 0.3:
        return "Messaging-first (WhatsApp)"
    if dominant == "video_streaming_gb" and dom_share > 0.32:
        # split by which sub-app dominates within this centroid is handled
        # at assignment time using the raw youtube/netflix ratio; default:
        return "Heavy Video streamer (YouTube)"
    if dominant == "social_media_gb" and dom_share > 0.32:
        return "Social scroller (TikTok)"
    return "Everyday all-rounder"


def discover_personas(df: pd.DataFrame, feats: pd.DataFrame, k: int = 12, seed: int = RNG_SEED):
    share_cols = [f"share_{s}" for s in SECTIONS]
    ratio_cols = ["yt_vs_netflix", "tiktok_vs_instagram"]
    X = feats[[f"log_{s}" for s in SECTIONS] + share_cols + ratio_cols]
    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)

    km = KMeans(n_clusters=k, random_state=seed, n_init=10)
    raw_labels = km.fit_predict(Xs)

    sil = silhouette_score(Xs, raw_labels)

    # stability across restarts
    km2 = KMeans(n_clusters=k, random_state=seed + 1, n_init=10)
    raw_labels2 = km2.fit_predict(Xs)
    stability_ari = adjusted_rand_score(raw_labels, raw_labels2)

    # Name each of the k raw clusters onto one of the 10 named personas,
    # splitting video/social clusters by their YT-vs-Netflix / TikTok-vs-IG
    # ratio so both members of each pair can appear.
    cluster_names = {}
    for c in range(k):
        mask = raw_labels == c
        if mask.sum() == 0:
            continue
        center_shares = feats.loc[mask, share_cols].mean()
        center_shares.index = SECTIONS
        total_gb = feats.loc[mask, "total_gb"].mean()
        name = name_cluster(center_shares, total_gb)

        if name == "Heavy Video streamer (YouTube)":
            ytr = df.loc[mask, "youtube_gb"].sum() / (df.loc[mask, "youtube_gb"].sum() + df.loc[mask, "netflix_gb"].sum() + 1e-6)
            name = "Heavy Video streamer (YouTube)" if ytr >= 0.5 else "Video streamer (Netflix)"
        if name == "Social scroller (TikTok)":
            ttr = df.loc[mask, "tiktok_gb"].sum() / (df.loc[mask, "tiktok_gb"].sum() + df.loc[mask, "instagram_gb"].sum() + 1e-6)
            name = "Social scroller (TikTok)" if ttr >= 0.5 else "Social scroller (Instagram)"

        cluster_names[c] = name

    persona = pd.Series([cluster_names[c] for c in raw_labels], index=df.index, name="persona")
    diag = {"silhouette": sil, "stability_ari": stability_ari, "scaler": scaler, "n_clusters_used": len(cluster_names)}
    return persona, diag


# ---------------------------------------------------------------------------
# 3. Classifier: LR vs RF vs HGB, 5-fold stratified CV
# ---------------------------------------------------------------------------
def train_classifier(feats: pd.DataFrame, y: pd.Series, seed: int = RNG_SEED):
    X_raw = feats.drop(columns=["total_gb"]).values
    clf_scaler = StandardScaler().fit(X_raw)
    X = clf_scaler.transform(X_raw)
    labels = sorted(y.unique())
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)

    models = {
        "LogisticRegression": LogisticRegression(max_iter=2000),
        "RandomForest": RandomForestClassifier(n_estimators=300, random_state=seed, n_jobs=-1),
        "ExtraTrees": ExtraTreesClassifier(n_estimators=400, random_state=seed, n_jobs=-1),
        "HistGradientBoosting": HistGradientBoostingClassifier(random_state=seed),
        "GradientBoosting": GradientBoostingClassifier(random_state=seed),
        "SVM_RBF": SVC(kernel="rbf", C=4.0, gamma="scale"),
        "MLP": MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=800, random_state=seed, early_stopping=True),
    }

    results = {}
    oof_preds = {}
    for name, model in models.items():
        preds = cross_val_predict(model, X, y, cv=cv, n_jobs=1)
        acc = accuracy_score(y, preds)
        macro_f1 = f1_score(y, preds, average="macro")
        fold_accs = []
        for _, test_idx in cv.split(X, y):
            fold_accs.append(accuracy_score(y.values[test_idx], preds[test_idx]))
        results[name] = {
            "accuracy": acc,
            "macro_f1": macro_f1,
            "fold_acc_min": min(fold_accs),
            "fold_acc_max": max(fold_accs),
        }
        oof_preds[name] = preds

    best_name = max(results, key=lambda n: results[n]["macro_f1"])
    best_model = models[best_name].fit(X, y)
    cm = confusion_matrix(y, oof_preds[best_name], labels=labels)
    report = classification_report(y, oof_preds[best_name], labels=labels, zero_division=0)

    return {
        "results": results,
        "best_name": best_name,
        "best_model": best_model,
        "scaler": clf_scaler,
        "labels": labels,
        "confusion_matrix": cm,
        "classification_report": report,
        "feature_columns": list(feats.drop(columns=["total_gb"]).columns),
    }


# ---------------------------------------------------------------------------
# 4. Package builder: S/M/L tiers per persona
# ---------------------------------------------------------------------------
def build_packages(df: pd.DataFrame, persona: pd.Series):
    total = df[SECTIONS].sum(axis=1)
    work = df.copy()
    work["persona"] = persona.values
    work["total_gb"] = total.values

    packages = {}
    for pname, group in work.groupby("persona"):
        if len(group) < 10:
            continue
        q1, q2 = group["total_gb"].quantile([1 / 3, 2 / 3])
        tiers = {
            "S": group[group["total_gb"] <= q1],
            "M": group[(group["total_gb"] > q1) & (group["total_gb"] <= q2)],
            "L": group[group["total_gb"] > q2],
        }

        prev_price = 0.0
        for tname in ["S", "M", "L"]:
            tgroup = tiers[tname]
            if len(tgroup) == 0:
                continue

            p85 = tgroup["total_gb"].quantile(0.85)
            pack_total_gb = round(p85 * 1.10, 2)
            coverage = (tgroup["total_gb"] <= pack_total_gb).mean()

            buckets = {}
            allocated = 0.0
            for s in SECTIONS:
                s85 = tgroup[s].quantile(0.85) * 1.10
                if s85 >= 2.0:
                    buckets[s] = round(s85, 2)
                    allocated += s85
            general_pool = max(0.0, round(pack_total_gb - allocated, 2))

            n_buckets = len(buckets)
            bucket_premium = min(0.12, 0.06 * n_buckets)
            formula_price = 5.27 * np.sqrt(max(pack_total_gb, 0.1)) * (1 + bucket_premium)

            existing_price, existing_src = cheapest_existing_offer(pack_total_gb)
            cap_price = 0.92 * existing_price
            price = min(formula_price, cap_price)
            price = max(price, prev_price)  # monotonic: L never cheaper than S/M
            price = round(price, 2)
            prev_price = price

            packages[(pname, tname)] = {
                "persona": pname,
                "tier": tname,
                "total_gb": pack_total_gb,
                "buckets_gb": buckets,
                "general_pool_gb": general_pool,
                "price_azn": price,
                "formula_price_azn": round(formula_price, 2),
                "existing_offer_price_azn": existing_price,
                "existing_offer_source": existing_src,
                "n_users_in_tier": len(tgroup),
                "coverage_within_tier": round(coverage, 4),
                "tier_gb_bounds": (round(float(q1 if tname == "S" else (q2 if tname == "L" else q1)), 2),
                                   round(float(q2 if tname != "L" else group["total_gb"].max()), 2)),
            }

    return packages


def assign_tier(total_gb: float, persona: str, packages: dict) -> str:
    candidates = [(t, packages[(persona, t)]) for t in ["S", "M", "L"] if (persona, t) in packages]
    if not candidates:
        return None
    fitting = [t for t, pkg in candidates if pkg["total_gb"] >= total_gb]
    if fitting:
        return min(fitting, key=lambda t: packages[(persona, t)]["total_gb"])
    return max(candidates, key=lambda x: x[1]["total_gb"])[0]


# ---------------------------------------------------------------------------
# 5. recommend(user)
# ---------------------------------------------------------------------------
def recommend(user_row: pd.Series, clf_bundle: dict, packages: dict, scaler=None):
    single = pd.DataFrame([user_row])
    feats = engineer_features(single)
    X = clf_bundle["scaler"].transform(feats[clf_bundle["feature_columns"]].values)
    persona = clf_bundle["best_model"].predict(X)[0]
    total_gb = feats["total_gb"].iloc[0]
    tier = assign_tier(total_gb, persona, packages)
    if tier is None:
        return {"persona": persona, "tier": None, "package": None, "reason": "no_package_for_persona"}
    pkg = packages[(persona, tier)]
    return {"persona": persona, "tier": tier, "total_gb_used": round(float(total_gb), 2), "package": pkg}


# ---------------------------------------------------------------------------
# 6. Economics evaluation
# ---------------------------------------------------------------------------
def economics_eval(df: pd.DataFrame, persona: pd.Series, packages: dict):
    total = df[SECTIONS].sum(axis=1)
    rows = []
    for i, uid in enumerate(df["user_id"]):
        p = persona.iloc[i]
        g = total.iloc[i]
        tier = assign_tier(g, p, packages)
        if tier is None:
            continue
        our_price = packages[(p, tier)]["price_azn"]
        existing_price, existing_src = cheapest_existing_offer(g)
        savings = existing_price - our_price
        rows.append(
            dict(user_id=uid, persona=p, tier=tier, total_gb=g, our_price=our_price,
                 existing_price=existing_price, existing_src=existing_src, user_savings=savings)
        )
    edf = pd.DataFrame(rows)
    return edf


def economics_summary(edf: pd.DataFrame) -> dict:
    return {
        "n_users": len(edf),
        "avg_user_savings_azn": round(edf["user_savings"].mean(), 3),
        "avg_operator_margin_change_azn": round(-edf["user_savings"].mean(), 3),
        "pct_users_who_save": round((edf["user_savings"] > 0).mean() * 100, 2),
        "pct_win_win": round(((edf["user_savings"] > 0) & (edf["user_savings"] < 0)).mean() * 100, 2),  # structurally 0, kept explicit
    }


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main():
    t0 = time.perf_counter()

    train = pd.read_csv("telecom_users.csv")
    hidden_train = pd.read_csv("telecom_users_hidden_types.csv")
    test_same = pd.read_csv("test_same_dist.csv")
    hidden_same = pd.read_csv("test_same_dist_hidden_types.csv")
    test_drift = pd.read_csv("test_drift_x1.3.csv")
    hidden_drift = pd.read_csv("test_drift_x1.3_hidden_types.csv")

    print("=" * 70)
    print("STAGE 2: Persona discovery (K-Means k=12 -> named personas)")
    print("=" * 70)
    feats_train = engineer_features(train)
    persona_train, diag = discover_personas(train, feats_train)
    ari_vs_hidden = adjusted_rand_score(hidden_train["hidden_type"], persona_train)
    print(f"Silhouette score: {diag['silhouette']:.3f}")
    print(f"Stability (ARI across two K-Means restarts): {diag['stability_ari']:.3f}")
    print(f"ARI vs hidden_type (generator ground truth, eval-only): {ari_vs_hidden:.3f}")
    print(f"Named personas produced: {diag['n_clusters_used']} / {len(NAMED_PERSONAS)} target names")
    print("\nPersona distribution:")
    print(persona_train.value_counts())

    print("\n" + "=" * 70)
    print("STAGE 3: Persona classifier (LR vs RF vs HGB, 5-fold stratified CV)")
    print("=" * 70)
    clf_bundle = train_classifier(feats_train, persona_train)
    for name, r in clf_bundle["results"].items():
        tag = "  <-- best" if name == clf_bundle["best_name"] else ""
        print(f"{name:22s} acc={r['accuracy']:.4f}  macroF1={r['macro_f1']:.4f}  "
              f"fold_range=[{r['fold_acc_min']:.4f},{r['fold_acc_max']:.4f}]{tag}")
    n_correct = int(round(clf_bundle["results"][clf_bundle["best_name"]]["accuracy"] * len(train)))
    print(f"\nBest model: {clf_bundle['best_name']} -> {n_correct}/{len(train)} correct on 5-fold OOF predictions")
    print("\nConfusion matrix (rows=true, cols=pred), labels order:")
    print(clf_bundle["labels"])
    print(clf_bundle["confusion_matrix"])

    print("\n" + "=" * 70)
    print("STAGE 4: Package builder (S/M/L per persona)")
    print("=" * 70)
    packages = build_packages(train, persona_train)
    print(f"Total packages built: {len(packages)}")
    for (pname, tname), pkg in sorted(packages.items()):
        buckets_str = ", ".join(f"{k.replace('_gb','')}={v}GB" for k, v in pkg["buckets_gb"].items())
        print(f"  {pname:32s} {tname}  {pkg['total_gb']:6.2f} GB  {pkg['price_azn']:6.2f} AZN  "
              f"(formula={pkg['formula_price_azn']}, cap_from={pkg['existing_offer_source']}@{pkg['existing_offer_price_azn']})  "
              f"[{buckets_str}] n={pkg['n_users_in_tier']} cov={pkg['coverage_within_tier']}")

    print("\n" + "=" * 70)
    print("STAGE 6: Economics evaluation (train population)")
    print("=" * 70)
    edf_train = economics_eval(train, persona_train, packages)
    summ_train = economics_summary(edf_train)
    print(json.dumps(summ_train, indent=2))
    user_tier_fit = (edf_train["total_gb"] <= edf_train.apply(lambda r: packages[(r["persona"], r["tier"])]["total_gb"], axis=1)).mean()
    print(f"Own tier pack covers user's usage: {user_tier_fit*100:.2f}% of train users")

    print("\n" + "=" * 70)
    print("STAGE 7a: Held-out test (same distribution, fresh seed)")
    print("=" * 70)
    feats_same = engineer_features(test_same)
    X_same = clf_bundle["scaler"].transform(feats_same[clf_bundle["feature_columns"]].values)
    pred_same = clf_bundle["best_model"].predict(X_same)
    persona_same_true_proxy, _ = discover_personas(test_same, feats_same)  # for coverage calc only
    acc_same_vs_cluster = accuracy_score(persona_same_true_proxy, pred_same)
    print(f"Classifier agreement with a fresh K-Means relabel on held-out same-dist data: {acc_same_vs_cluster*100:.2f}%")
    edf_same = economics_eval(test_same, pd.Series(pred_same), packages)
    cover_same = (edf_same["total_gb"] <= edf_same.apply(lambda r: packages[(r["persona"], r["tier"])]["total_gb"], axis=1)).mean()
    print(f"Own tier pack covers: {cover_same*100:.2f}% of same-dist test users")
    print(json.dumps(economics_summary(edf_same), indent=2))

    print("\n" + "=" * 70)
    print("STAGE 7b: Drift test (usage x1.3)")
    print("=" * 70)
    feats_drift = engineer_features(test_drift)
    X_drift = clf_bundle["scaler"].transform(feats_drift[clf_bundle["feature_columns"]].values)
    pred_drift = clf_bundle["best_model"].predict(X_drift)
    edf_drift = economics_eval(test_drift, pd.Series(pred_drift), packages)
    cover_drift = (edf_drift["total_gb"] <= edf_drift.apply(lambda r: packages[(r["persona"], r["tier"])]["total_gb"], axis=1)).mean()
    print(f"Own tier pack covers: {cover_drift*100:.2f}% of x1.3-drift test users (fixed packages, not retrained)")
    print(json.dumps(economics_summary(edf_drift), indent=2))

    print("\n" + "=" * 70)
    print("STAGE 8a: Hand-crafted demo users")
    print("=" * 70)
    demo_users = pd.DataFrame([
        dict(user_id=900001, social_media_gb=1.0, tiktok_gb=0.3, instagram_gb=0.3, video_streaming_gb=1.0,
             youtube_gb=0.5, netflix_gb=0.3, communication_gb=0.5, whatsapp_gb=0.4, collaboration_gb=0.1,
             teams_gb=0.05, ai_apps_gb=0.1, chatgpt_gb=0.05, claude_gb=0.03, gemini_gb=0.01, gaming_gb=0.1,
             expected="Light user"),
        dict(user_id=900002, social_media_gb=2.0, tiktok_gb=0.5, instagram_gb=0.5, video_streaming_gb=2.0,
             youtube_gb=1.0, netflix_gb=0.5, communication_gb=1.0, whatsapp_gb=0.8, collaboration_gb=0.2,
             teams_gb=0.1, ai_apps_gb=0.3, chatgpt_gb=0.15, claude_gb=0.1, gemini_gb=0.03, gaming_gb=45.0,
             expected="Gamer"),
        dict(user_id=900003, social_media_gb=2.0, tiktok_gb=0.5, instagram_gb=0.5, video_streaming_gb=3.0,
             youtube_gb=1.5, netflix_gb=1.0, communication_gb=1.5, whatsapp_gb=1.2, collaboration_gb=1.0,
             teams_gb=0.5, ai_apps_gb=17.0, chatgpt_gb=8.0, claude_gb=6.0, gemini_gb=2.0, gaming_gb=0.3,
             expected="AI power user"),
        dict(user_id=900004, social_media_gb=2.0, tiktok_gb=0.5, instagram_gb=0.5, video_streaming_gb=2.0,
             youtube_gb=1.0, netflix_gb=0.5, communication_gb=6.5, whatsapp_gb=6.0, collaboration_gb=0.2,
             teams_gb=0.1, ai_apps_gb=0.2, chatgpt_gb=0.1, claude_gb=0.05, gemini_gb=0.02, gaming_gb=0.3,
             expected="Messaging-first (WhatsApp)"),
        dict(user_id=900005, social_media_gb=2.0, tiktok_gb=0.5, instagram_gb=0.5, video_streaming_gb=23.0,
             youtube_gb=3.0, netflix_gb=19.0, communication_gb=1.5, whatsapp_gb=1.2, collaboration_gb=0.3,
             teams_gb=0.1, ai_apps_gb=0.2, chatgpt_gb=0.1, claude_gb=0.05, gemini_gb=0.02, gaming_gb=0.5,
             expected="Video streamer (Netflix)"),
        dict(user_id=900006, social_media_gb=10.0, tiktok_gb=7.0, instagram_gb=2.5, video_streaming_gb=3.0,
             youtube_gb=1.5, netflix_gb=1.0, communication_gb=1.5, whatsapp_gb=1.2, collaboration_gb=0.2,
             teams_gb=0.1, ai_apps_gb=0.2, chatgpt_gb=0.1, claude_gb=0.05, gemini_gb=0.02, gaming_gb=0.5,
             expected="Social scroller (TikTok)"),
    ])
    n_right = 0
    for _, row in demo_users.iterrows():
        rec = recommend(row.drop(["expected"]), clf_bundle, packages)
        ok = rec["persona"] == row["expected"]
        n_right += int(ok)
        mark = "OK" if ok else "MISS"
        print(f"[{mark}] user {int(row['user_id'])}: expected={row['expected']!r:32s} got={rec['persona']!r:32s} "
              f"tier={rec['tier']} price={rec['package']['price_azn'] if rec['package'] else None}")
    print(f"\nHand-crafted demo users correct: {n_right}/{len(demo_users)}")

    elapsed = time.perf_counter() - t0
    n_total_scored = len(train) + len(test_same) + len(test_drift)
    print("\n" + "=" * 70)
    print("STAGE: Running time")
    print("=" * 70)
    print(f"Full pipeline wall time: {elapsed:.1f}s for {n_total_scored} users "
          f"(gen+cluster+CV+package-build+econ+holdout+drift)")
    print(f"Approx per-user scoring time (post-training): {(elapsed / n_total_scored) * 1000:.4f} ms/user")

    with open("run_summary.json", "w") as fh:
        json.dump({
            "silhouette": diag["silhouette"],
            "stability_ari": diag["stability_ari"],
            "ari_vs_hidden_type": ari_vs_hidden,
            "classifier_results": {k: {kk: float(vv) for kk, vv in v.items()} for k, v in clf_bundle["results"].items()},
            "best_model": clf_bundle["best_name"],
            "n_packages": len(packages),
            "economics_train": summ_train,
            "economics_same_dist": economics_summary(edf_same),
            "economics_drift": economics_summary(edf_drift),
            "own_tier_coverage_train_pct": round(user_tier_fit * 100, 2),
            "own_tier_coverage_same_dist_pct": round(cover_same * 100, 2),
            "own_tier_coverage_drift_pct": round(cover_drift * 100, 2),
            "demo_users_correct": f"{n_right}/{len(demo_users)}",
            "pipeline_wall_time_s": elapsed,
        }, fh, indent=2)
    print("\nWrote run_summary.json")

    print("\n" + "=" * 70)
    print("STAGE: Export deployment artifact (for TypeScript port)")
    print("=" * 70)
    best_model = clf_bundle["best_model"]
    if isinstance(best_model, LogisticRegression):
        export = {
            "feature_columns": clf_bundle["feature_columns"],
            "scaler_mean": clf_bundle["scaler"].mean_.tolist(),
            "scaler_scale": clf_bundle["scaler"].scale_.tolist(),
            "classes": list(best_model.classes_),
            "coef": best_model.coef_.tolist(),
            "intercept": best_model.intercept_.tolist(),
            "packages": {
                f"{p}::{t}": {
                    "persona": pkg["persona"],
                    "tier": pkg["tier"],
                    "total_gb": pkg["total_gb"],
                    "buckets_gb": pkg["buckets_gb"],
                    "general_pool_gb": pkg["general_pool_gb"],
                    "price_azn": pkg["price_azn"],
                }
                for (p, t), pkg in packages.items()
            },
            "tier_order": ["S", "M", "L"],
        }
        with open("model_export.json", "w") as fh:
            json.dump(export, fh, indent=2)
        print("Exported model_export.json (LogisticRegression weights + packages) for TypeScript port.")
    else:
        print(f"Best model was {clf_bundle['best_name']}, not LogisticRegression -- "
              f"skipping direct weight export (tree/SVM/MLP models aren't trivially portable to TS).")


if __name__ == "__main__":
    main()
